M48
; DRILL file KiCad 10.0.0 date 2026-03-27T10:38:08
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-27T10:38:08+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
%
G90
G05
T1
X86.01Y-65.47
X87.28Y-132.777
X91.79Y-65.47
X93.06Y-132.777
T2
X52.705Y-89.662
X52.705Y-98.262
M30
